# Generated by Django 6.0.5 on 2026-06-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='authors',
        ),
    ]
